########## Configuration Start ##########

server:
  port: 8010

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka-server
  client:
    serviceUrl:
      defaultZone: http://${server.address}:${server.port}/eureka/
    registerWithEureka: true
    fetchRegistry: true

logging:
  config: classpath:logback.xml

########## Cofiguration End ##########
