#
server:
  port: 7101
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-eureka
  main:
    web-application-type: servlet
    banner-mode: console
  #====================
  #（▲）Http Basic认证
  #====================
  security:
    user:
      name: wzj
      password: 123
  #
  profiles:
    active: eureka
