#
server:
  port: 7010
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-eureka

# 注册中心配置
eureka:
  instance:
    hostname:
    instance-id:
    lease-renewal-interval-in-seconds: 5
    #lease-expiration-duration-in-seconds: 15
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
