########## Config Start ##########
###
server:
  address: 127.0.0.1
  port: 7000
###
spring:
  application:
    name: service-eureka
###
eureka:
  server:
    enableSelfPreservation: false
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
###
logging:
  config: classpath:logback.xml
########## Config End ##########
