#
server:
  port: 7010
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-eureka

# 注册中心配置
eureka:
  instance:
    hostname: 127.0.0.1
#    instance-id:
    lease-renewal-interval-in-seconds: 5
    #lease-expiration-duration-in-seconds: 15
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #是否开启自我保护
    enable-self-preservation: false
    #指定EvictionTask定时任务调用频率，用于剔除过期实例
    eviction-interval-timer-in-ms: 5
    #指定每分钟需要收到续约次数的阈值
    renewal-percent-threshold: 0.45
    #
    renewal-threshold-update-interval-ms: 1000

