########## Spring Boot Configuration Start ##########
##
server:
  address: 172.16.23.77
  port: 8010
##
spring:
  application:
    name: eureka-server
##
eureka:
  instance:
    hostname: eureka-server
  client:
    serviceUrl:
      defaultZone: http://${server.address}:${server.port}/eureka/
    registerWithEureka: true
    fetchRegistry: true
##
logging:
  config: classpath:logback.xml
########## Spring Boot Cofiguration End ##########
