#
server:
  port: 3333
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-eureka
  main:
    web-application-type: servlet
    banner-mode: "console"
  profiles:
    active: eureka
