#
eureka:
  #实例配置
  instance:
    hostname: @eureka.host.name@
    instance-id: ${eureka.instance.hostname}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  #客户端配置
  client:
    service-url:
      defaultZone: @eureka.server.list@
    register-with-eureka: false
    fetch-registry: false
    enabled: true
  #服务端配置
  server:
    #（★）续约！！！
    #（无效服务）剔除时间间隔，默认60秒
    eviction-interval-timer-in-ms: 5000
    #希望客户端续约时间间隔，默认30秒
    expected-client-renewal-interval-seconds: 30

    #（★）保护机制！！！
    #是否启用自我保护机制，默认true
    enable-self-preservation: false
    #续约阈值更新间隔，默认15分钟
    renewal-threshold-update-interval-ms: 15000
    #续约阈值百分比，默认0.85；即15分钟内的比例小于0.85，则开启自我保护机制
    #在此期间不会清除已注册的任何服务（即便是无效服务）
    renewal-percent-threshold: 0.85

    #（）响应缓存
    #
    use-read-only-response-cache: false
    #响应缓存自动过期时间
    response-cache-auto-expiration-in-seconds: 180
    #响应缓存更新时间间隔
    response-cache-update-interval-ms: 0
    initial-capacity-of-response-cache: 1000

    #（）集群连接
    #对等节点连接超时时间
    peer-node-connect-timeout-ms: 1
    #对等节点读取超时时间
    peer-node-read-timeout-ms: 200
    #（）集群复制
    #是否开启复制请求压缩，默认false
    enable-replicated-request-compression: false
    #复制重试次数，默认5次
    number-of-replication-retries: 5
    #server启动时，不能从对等节点获取instance注册信息的情况，应等待多长时间
    wait-time-in-ms-when-sync-empty: 0

    #自定义工具配置
    #Json编解码器名称
    #json-codec-name:
    #属性解析器名称
    #property-resolver:
    #Xml编解码器名称
    #xml-codec-name:
#    delta-retention-timer-interval-in-ms: