###
server:
  address: 127.0.0.1
  port: 7000
###
spring:
  application:
    name: springcloud-eureka
###
eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${sercer.port}}
  server:
    #自我保护
    enable-self-preservation: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
###
logging:
  config: classpath:logback.xml
