#
server:
  port: @server.port@
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-eureka
  main:
    web-application-type: servlet
    banner-mode: off
  #（★）HttpBasic认证
  security:
    user:
      name: admin
      password: 123
  #
  profiles:
    active: eureka