version: '3'
services:
  study-springcloud-eureka1:
    image: study/study-springcloud-eureka:1
    restart: always
    ports:
      - 7101:7100
    environment:
      - eureka.instance.hostname=eureka-server1
      - EUREKA_SERVER_LIST=http://eureka-server2:7100/eureka/
    volumes:
      - /xdfapp:/xdfapp
    networks:
      - demo_net
  study-springcloud-eureka2:
    image: study/study-springcloud-eureka:1
    restart: always
    ports:
      - 7102:7100
    environment:
      - eureka.instance.hostname=eureka-server2
      - EUREKA_SERVER_LIST=http://eureka-server1:7100/eureka/
    volumes:
      - /xdfapp:/xdfapp
    networks:
      - demo_net
  study-springcloud-provider1:
    image: study/study-springcloud-provider:1
    restart: always
    ports:
      - 7201:7200
    environment:
      - EUREKA_SERVER_LIST=http://114.67.102.8:7101/eureka/,http://114.67.102.8:7102/eureka/
    volumes:
      - /xdfapp:/xdfapp
    networks:
      - demo_net
  study-springcloud-provider2:
    image: study/study-springcloud-provider:1
    restart: always
    ports:
      - 7202:7200
    environment:
      - EUREKA_SERVER_LIST=http://114.67.102.8:7101/eureka/,http://114.67.102.8:7102/eureka/
    volumes:
      - /xdfapp:/xdfapp
    networks:
      - demo_net
networks:
  demo_net:
    external: true