version: '3.6'
services:
  study-springcloud-eureka1:
    image: study/study-springcloud-eureka:1
    restart: always
    hostname: eureka-server1
    ports:
      - "7101:7101"
    volumes:
      - /xdfapp:/xdfapp
    networks:
      - study_net
  study-springcloud-eureka2:
    image: study/study-springcloud-eureka:1
    restart: always
    hostname: eureka-server2
    ports:
      - "7102:7102"
    volumes:
      - /xdfapp:/xdfapp
    networks:
      - study_net

networks:
  study_net:
    external: true