version: '3'
services:
  study-springcloud-eureka1:
    image: study/study-springcloud-eureka:1
    restart: always
    ports:
      - 7101:7100
    environment:
      - eureka.instance.name=eureka-server1
      - ADDITIONAL_EUREKA_SERVER_LIST=http://eureka-server2:7102/eureka/
    volumes:
      - /xdfapp:/xdfapp
    networks:
      - demo_net
  study-springcloud-eureka2:
    image: study/study-springcloud-eureka:1
    restart: always
    ports:
      - 7102:7100
    environment:
      - eureka.instance.name=eureka-server2
      - ADDITIONAL_EUREKA_SERVER_LIST=http://eureka-server1:7101/eureka/
    volumes:
      - /xdfapp:/xdfapp
    networks:
      - demo_net
  study-springcloud-eureka3:
    image: study/study-springcloud-eureka:1
    restart: always
    ports:
      - 7103:7100
    environment:
      - eureka.instance.name=eureka-server3
      - ADDITIONAL_EUREKA_SERVER_LIST=http://eureka-server1:7101/eureka/
    volumes:
      - /xdfapp:/xdfapp
    networks:
      - demo_net
networks:
  demo_net:
    external: true