version: '3.6'
services:
  eureka-server1:
    image: study/study-springcloud-eureka:1
    restart: always
    hostname: eureka-server1
    ports:
      - "7101:7101"
    environment:
      - SERVER_PORT=7101
      #- eureka.instance.hostname=eureka-server1
      - EUREKA_SERVER_LIST=http://114.67.102.8:7102/eureka/
    volumes:
      - /xdfapp:/xdfapp
    networks:
      - study_net
  eureka-server2:
    image: study/study-springcloud-eureka:1
    restart: always
    hostname: eureka-server2
    ports:
      - "7102:7102"
    environment:
      - SERVER_PORT=7102
      #- eureka.instance.hostname=eureka-server2
      - EUREKA_SERVER_LIST=http://114.67.102.8:7101/eureka/
    volumes:
      - /xdfapp:/xdfapp
    networks:
      - study_net

networks:
  study_net:
    external: true